name: update-data

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run update script
        run: python Scripts/run_scripts.py
      - name: Push changes
        run: |
          git config --global user.name "ajgafford"
          git config --global user.email "andrew.gafford@gmail.com"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/ajgafford/rockies-loss-tracker.git
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated data update"
          git push origin main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}